apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: #{APP_NAME}#-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "#{PVC_SIZE}#Gi"
  storageClassName: "azurefile-csi"
