apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resourcesquota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.storage: #{PVC_SIZE}#Gi
    configmaps: "10"
    persistentvolumeclaims: "1"
    pods: "10"
    replicationcontrollers: "10"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
