# This is a basic workflow to help you get started with Actions

name: Create new repository

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: New Repository Name
        type: string
        required: true

permissions:
  id-token: write
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run az commands
        run: |
          echo "AZURE_APP_ID=$(az ad app create --display-name ${{ github.event.inputs.name }} --query "id" | tr -d '"')" >> $GITHUB_ENV

      - name: Echo Env variable
        run: echo $AZURE_APP_ID

#      - name: Azure CLI script
#        uses: azure/CLI@v1
#        with:
#          azcliversion: latest
#          inlineScript: |
#            az ad app create --display-name ${{ github.event.inputs.name }} --query []."id" | awk -F '"' '{print $2}'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.

      # run gh cli to manage new repo
#      - run: |
#          gh repo create ${{ github.event.inputs.name }} --template alexcwchan/aks_template --private
#          gh secret set AKS_TOKEN --repo alexcwchan/${{ github.event.inputs.name }} --body "$token"
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#          token: "123"

