name: Create AKS App and repository

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      appname:
        description: New Application Name
        type: string
        required: true

permissions:
  id-token: write
  contents: read
#  actions: read

#env:
#  APP_NAME: ${{ github.event.inputs.appname }}
#  AZURE_APP_NAME: aks-app-${{ github.event.inputs.appname }}
#  AZURE_ACR_TOKEN: "aks-app-${{ github.event.inputs.appname }}"

jobs:

  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      ns_check: ${{ steps.ns_check.outputs.status }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      
    - name: Azure login OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.34'

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER }}
        admin: false
        use-kubelogin: true

    - name: Check namespace status
      id: ns_check
      run: |
        echo "status=$(kubectl get namespace | grep '^${{ github.event.inputs.appname }} ' | wc -l)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: init
    #if: ${{ needs.init.outputs.ns_check }} = 0

    steps:
      - run: echo ${{ needs.init.outputs.ns_check }}

#    - name: Azure login OIDC
#      uses: azure/login@v1
#      with:
#        client-id: ${{ secrets.AZURE_CLIENT_ID }}
#        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#    - uses: azure/use-kubelogin@v1
#      with:
#        kubelogin-version: 'v0.0.34'

#    - name: Set AKS context
#      uses: azure/aks-set-context@v3
#      with:
#        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
#        cluster-name: ${{ secrets.AKS_CLUSTER }}
#        admin: false
#        use-kubelogin: true

#    - name: Check namespace status
#      run: |
#        kubectl get namespace

#    - name: Run kubectl command
#      run: |
#        kubectl create namespace for-aks-admin


#    - name: Replace token with env variables
#      uses: cschleiden/replace-tokens@v1
#      with:
#        tokenPrefix: '#{'
#        tokenSuffix: '}#'
#        files: '["./federated-credential.json"]'
#      env:
#        APP_NAME: ${{ env.APP_NAME }}



#    - name: Register an App
#      run: |
#        echo "AZURE_APP_ID=$(az ad app create --display-name ${{ env.AZURE_APP_NAME }} --query "id" | tr -d '"')" >> $GITHUB_ENV

#    - name: Create Federated Credential
#      run: |
#        az ad app federated-credential create --id ${{ env.AZURE_APP_ID }} --parameters federated-credential.json

#    - name: Create Token for Azure Container Registry
#      run: |
#        az acr token create --name ${{ env.AZURE_ACR_TOKEN }} --registry acrforhkusttest --repository ${{ env.AZURE_APP_NAME }} content/write content/read

#      - name: Echo Env variable
#        run: |
#          echo $APP_NAME
#          echo $AZURE_APP_ID
#          echo $AZURE_APP_NAME
#          echo $AZURE_ACR_TOKEN


#      - name: Azure CLI script
#        uses: azure/CLI@v1
#        with:
#          azcliversion: latest
#          inlineScript: |
#            az ad app create --display-name ${{ github.event.inputs.name }} --query []."id" | awk -F '"' '{print $2}'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.

      # run gh cli to manage new repo
#      - run: |
#          gh repo create ${{ github.event.inputs.name }} --template alexcwchan/aks_template --private
#          gh secret set AKS_TOKEN --repo alexcwchan/${{ github.event.inputs.name }} --body "$token"
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#          token: "123"

