name: Delete Azure Service Principal

on:
  workflow_dispatch:
    inputs:
      spname:
        description: Service Principal ID
        required: true

permissions:
  id-token: write
  contents: read
#  actions: read

jobs:

  initCheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Azure login OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Check Azure App
      id: app_check
      run: echo "status=$(az ad sp delete  --id ${{ inputs.spname }} --output tsv)" >> $GITHUB_OUTPUT

    - name: Display check status
      run: |
        echo "App check: ${{ steps.app_check.outputs.status }}"