name: Delete AKS App

on:
  workflow_dispatch:
    inputs:
      appname:
        description: Application Name (e.g. app1)
        required: true

permissions:
  id-token: write
  contents: read

env:
  APP_NAME: aksapp-${{ inputs.appname }}
  ACR_REPO: aksapp/${{ inputs.appname }}

jobs:

  initCheckDev:
    runs-on: ubuntu-latest
    outputs:
      app_check: ${{ steps.app_check.outputs.status }}
      sp_check: ${{ steps.sp_check.outputs.status }}
      acrrepo_check: ${{ steps.acrrepo_check.outputs.status }}
      acrtoken_check: ${{ steps.acrtoken_check.outputs.status }}
      acrscope_check: ${{ steps.acrscope_check.outputs.status }}
      ns_check: ${{ steps.ns_check.outputs.status }}
      githubrepo_check: ${{ steps.githubrepo_check.outputs.status }}

    steps:
    - name: Azure login OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: kubelogin with AKS
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.34'

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ vars.AKS_CLUSTER }}
        admin: false
        use-kubelogin: true

    - name: Check Azure App
      id: app_check
      run: echo "status=$(az ad app list --filter "displayname eq '${{ env.APP_NAME }}'" --query [].appId -o tsv)" >> $GITHUB_OUTPUT

    - name: Check Azure SP
      id: sp_check
      run: echo "status=$(az ad sp show --id ${{ steps.app_check.outputs.status }} --query id -o tsv)" >> $GITHUB_OUTPUT

    - name: Check ACR repository
      id: acrrepo_check
      run: echo "status=$(az acr repository show -n ${{ vars.ACR_REGISTRY }} --repository ${{ env.ACR_REPO }} -o tsv | wc -l)" >> $GITHUB_OUTPUT

    - name: Check ACR token
      id: acrtoken_check
      run: echo "status=$(az acr token show -r ${{ vars.ACR_REGISTRY }} -n ${{ env.APP_NAME }} -o tsv | wc -l)" >> $GITHUB_OUTPUT

    - name: Check ACR scope map
      id: acrscope_check
      run: echo "status=$(az acr scope-map show -r ${{ vars.ACR_REGISTRY }} -n ${{ env.APP_NAME }}-scope-map -o tsv | wc -l)" >> $GITHUB_OUTPUT

    - name: Check AKS namespace
      id: ns_check
      run: echo "status=$(kubectl get namespace ${{ env.APP_NAME }} --ignore-not-found --no-headers | wc -l)" >> $GITHUB_OUTPUT

    - name: Check Github repository
      id: githubrepo_check
      run: echo "status=$(gh repo list ${{ vars.GH_ORG }} --json name | grep '\"${{ env.APP_NAME }}\"' | wc -l)" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Display check status
      run: |
        echo "App check: ${{ steps.app_check.outputs.status }}"
        echo "SP check: ${{ steps.sp_check.outputs.status }}"
        echo "ARC repository check: ${{ steps.acrrepo_check.outputs.status }}"
        echo "ACR token check: ${{ steps.acrtoken_check.outputs.status }}"
        echo "ACR scope map check: ${{ steps.acrscope_check.outputs.status }}"
        echo "Namespace check: ${{ steps.ns_check.outputs.status }}"
        echo "Github repository check: ${{ steps.githubrepo_check.outputs.status }}"


  removeDev:
    runs-on: ubuntu-latest
    needs: initCheckDev
    # only run this step if all checks return true
    if: |-
      ${{
        needs.initCheckDev.outputs.app_check != '' &&
        needs.initCheckDev.outputs.sp_check != '' &&
        needs.initCheckDev.outputs.acrtoken_check == '1' &&
        needs.initCheckDev.outputs.acrscope_check == '1' &&
        needs.initCheckDev.outputs.ns_check == '1' &&
        needs.initCheckDev.outputs.githubrepo_check == '1'
      }}

    steps:
    - name: Azure login OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: kubelogin with AKS
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.34'

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ vars.AKS_CLUSTER }}
        admin: false
        use-kubelogin: true

    - name: Delete Github repository
      run: |
        gh repo delete ${{ vars.GH_ORG }}/${{ env.APP_NAME }} --yes
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Delete role assignment and AKS namespace
      run: |
        az role assignment delete --role "Azure Kubernetes Service Cluster User Role" --assignee ${{ needs.initCheckDev.outputs.app_check }} --scope /subscriptions/8fec5943-6772-4aa8-a1aa-59ef7483fd2b/resourcegroups/rg-dev-eas-aks-01/providers/Microsoft.ContainerService/managedClusters/aks-zup2kwh4fwbse
        az role assignment delete --role "Azure Kubernetes Service RBAC Writer" --assignee ${{ needs.initCheckDev.outputs.app_check }} --scope /subscriptions/8fec5943-6772-4aa8-a1aa-59ef7483fd2b/resourcegroups/rg-dev-eas-aks-01/providers/Microsoft.ContainerService/managedClusters/aks-zup2kwh4fwbse/namespaces/${{ env.APP_NAME }}
        kubectl delete namespace ${{ env.APP_NAME }}

    - name: Delete ACR token
      run: az acr token delete -n ${{ env.APP_NAME }} -r ${{ vars.ACR_REGISTRY }} -y -o tsv

    - name: Delete ACR scope map
      run: az acr scope-map delete -n ${{ env.APP_NAME }}-scope-map -r ${{ vars.ACR_REGISTRY }} -y -o tsv

    - name: Delete ACR repository
      run: az acr repository delete -n ${{ env.ACR_REPO }} --repository ${{ vars.ACR_REGISTRY }}

    - name: Delete Azure SP
      run: az ad sp delete --id ${{ needs.initCheckDev.outputs.sp_check }} -o tsv

    - name: Delete Azure App
      run: az ad app delete --id ${{ needs.initCheckDev.outputs.app_check }} -o tsv

#    - name: Add inventory record
#      run: |
#        curl -k 'https://aks-backend.beatricehk.com/addApp/${{ inputs.appname }}?url=${{ inputs.url}}&faculty_in_charge=${{ inputs.faculty_in_charge }}&staff_in_charge=${{ inputs.staff_in_charge }}&department=${{ inputs.department }}&password=${{ env.ACR_TOKEN_PW }}'
