name: Init Check Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      appenv:
        description: Environment
        required: true
      appname:
        description: Application Name
        required: true
      acrrepo:
        description: ACR Repository Name
        required: true

permissions:
  id-token: write
  contents: read

jobs:

  initCheck:
    runs-on: ubuntu-latest
    #environment: ${{ inputs.appenv }}
    outputs:
      initCheck_status: ${{ steps.check_status.outputs.status }}

    steps:
    - name: Azure login OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: kubelogin with AKS
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.34'

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ vars.AKS_CLUSTER }}
        admin: false
        use-kubelogin: true

    - name: Check Azure App
      run: echo "app_check=$(az ad app list --filter "displayname eq '${{ inputs.appname }}'" -o tsv | wc -l)" >> $GITHUB_ENV

    - name: Check Azure SP
      run: echo "sp_check=$(az ad sp list --display-name '${{ inputs.appname }}' -o tsv | wc -l)" >> $GITHUB_ENV

    - name: Check ACR repository
      run: echo "acrrepo_check=$(az acr repository list -n ${{ vars.ACR_REGISTRY }} --query "[?contains(@, '${{ inputs.acrrepo }}')]" -o tsv | wc -l)" >> $GITHUB_ENV

    - name: Check ACR token
      run: echo "acrtoken_check=$(az acr token show -r ${{ vars.ACR_REGISTRY }} -n ${{ inputs.appname }} -o tsv | wc -l)" >> $GITHUB_ENV

    - name: Check ACR scope map
      run: echo "acrscope_check=$(az acr scope-map show -r ${{ vars.ACR_REGISTRY }} -n ${{ inputs.appname }}-scope-map -o tsv | wc -l)" >> $GITHUB_ENV

    - name: Check AKS namespace
      run: echo "ns_check=$(kubectl get namespace ${{ inputs.appname }} --ignore-not-found --no-headers | wc -l)" >> $GITHUB_ENV

    - name: Check Github repository
      run: echo "githubrepo_check=$(gh repo list ${{ vars.GH_ORG }} --json name | grep '\"${{ inputs.appname }}\"' | wc -l)" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: export check status
      id: check_status
      run: |-
        if [ ${{ env.app_check }} == '0' ] && \
           [ ${{ env.sp_check }} == '0' ] && \
           [ ${{ env.acrrepo_check }} == '0' ] && \
           [ ${{ env.acrtoken_check }} == '0' ] && \
           [ ${{ env.acrscope_check }} == '0' ] && \
           [ ${{ env.ns_check }} == '0' ] && \
           [ ${{ env.githubrepo_check }} == '0' ]
        then
          echo "status=0" >> $GITHUB_OUTPUT
        else
          echo "status=1" >> $GITHUB_OUTPUT
        fi

    - name: Display check status
      run: |
        echo "App check: ${{ env.app_check }}"
        echo "SP check: ${{ env.sp_check }}"
        echo "ARC repository check: ${{ env.acrrepo_check }}"
        echo "ACR token check: ${{ env.acrtoken_check }}"
        echo "ACR scope map check: ${{ env.acrscope_check }}"
        echo "Namespace check: ${{ env.ns_check }}"
        echo "Github repository check: ${{ env.githubrepo_check }}"
        echo "Overall check: ${{ steps.check_status.outputs.status }}"
