name: Test reusable workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  APP_NAME: aksapp-${{ inputs.appname }}
  ACR_REPO: aksapp/${{ inputs.appname }}

jobs:

  initCheckProd:
    uses: ./.github/workflows/initCheck.yml
    with:
      
