name: Test reusable workflow

on:
  workflow_dispatch:
    inputs:
      appname:
        description: Application Name (e.g. app1, lower case alphanumeric characters or '-')
        required: true

permissions:
  id-token: write
  contents: read

env:
  APP_NAME: aksapp-${{ inputs.appname }}
  ACR_REPO: aksapp/${{ inputs.appname }}

jobs:

  get-env-vars:
    name: Get Environment vars as output
    runs-on: Ubuntu-latest
    outputs:
      APP_NAME: ${{ env.APP_NAME }}
      ACR_REPO: ${{ env.ACR_REPO }}
    steps:
      - run: echo ''

  initCheckProd:
    needs: get-env-vars
    uses: ./.github/workflows/initCheck.yml
    with:
      appenv: prod
      appname: ${{ needs.get-env-vars.outputs.APP_NAME }}
      acrrepo: ${{ needs.get-env-vars.outputs.ACR_REPO }}
      AKS_CLUSTER: ${{ vars.AKS_CLUSTER }}
      ACR_REGISTRY: ${{ vars.ACR_REGISTRY }}
      AKS_RESOURCE_GROUP: ${{ vars.AKS_RESOURCE_GROUP }}
      GH_ORG: ${{ vars.GH_ORG }}
    secrets: inherit
#      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  deployProd:
    runs-on: Ubuntu-latest
    needs: initCheckProd
    steps:
      - run: echo ${{ needs.initCheckProd.outputs.initCheck_status }}
